[package]
name = "ccps506_poker"
version = "0.1.0"
edition = "2021"
"author" = "Moses Munyoki"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
